on: [push]

name: CI build

jobs:
  build:
    name: Build for ${{ matrix.platform.os_name }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os_name: Linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: rs_sxcks
            asset_name: rs_sxcks-linux-amd64
          - os_name: Windows-x86_64
            os: ubuntu-latest
            target: x86_64-pc-windows-gnu
            artifact_name: rs_sxcks.exe
            asset_name: rs_sxcks-windows-amd64.exe
          - os_name: Web
            os: ubuntu-latest
            target: wasm32-unknown-unknown
            artifact_name: rs_sxcks.wasm
            asset_name: rs_sxcks-web-wasm32.wasm
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - run: sudo apt-get update && sudo apt-get install libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev libssl-dev libgtk-3-dev libatk1.0-0 librust-atk-sys-dev
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: "build"
          target: ${{ matrix.platform.target }}
          toolchain: ${{ matrix.toolchain }}
          args: "--release"
          strip: true
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.platform.asset_name }}
          path: target/${{ matrix.platform.target }}/release/${{ matrix.platform.artifact_name }}
      - name: Release
        uses: svenstaro/upload-release-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.platform.target }}/release/${{ matrix.platform.artifact_name }}
          asset_name: ${{ matrix.platform.asset_name }}
          tag: ${{ github.ref }}

